export enum tables {
    BotDefinitions = "bot_definitions",
    BotInstances = "bot_instances",
    BotRuns = "bot_runs",
    Events = "events",
    Exchanges = "exchanges",
    Orders = "orders",
    OrderFills = "order_fills",
    OrderStates = "order_states",
    Plans = "plans",
    PlanModes = "plan_modes",
    PlanRuns = "plan_runs",
    Prices = "prices",
    TimeResolutions = "time_resolutions",
    TradeSymbols = "symbols",
    TradeSymbolTypes = "symbol_types",
    Users = "users",
    UserIdentities = "user_identities",
    UserInvites = "user_invites",
    Workspaces = "workspaces",
}
