parameters:
  - name: environment
    type: string
    default: dev

jobs:
  - deployment: deploy
    displayName: Deploy to AKS
    environment: $(environment)
    pool:
      vmImage: "Ubuntu-latest"

    strategy:
      runOnce:
        deploy:
          steps:

            # Download the artifact with the stamped version and configuration values
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: "current"
                downloadType: "single"
                artifactName: $(artifactName)
                downloadPath: "$(System.ArtifactsDirectory)"

            # Generate the appropriate K8S config for the environment
            - script: "kubectl kustomize $(Build.ArtifactStagingDirectory)/$(artifactName)/k8s/overlays/${{ parameters.environment }} > $(Build.ArtifactStagingDirectory)/$(artifactName)/manifest.yml"
              displayName: "Generate K8S config"

            - task: KubernetesManifest@0
              inputs:
                action: "deploy"
                kubernetesServiceConnection: $(kubernetesServiceConnection)
                manifests: "$(Build.ArtifactStagingDirectory)/$(artifactName)/$(manifestPath)"
                namespace: ${{ parameters.environment }}
                useClusterAdmin: true
