import env from "../env";
import { BotResultsEntity } from "../../common/entities/BotResultsEntity";
import { BotResults } from "../../common/models/bots/BotResults";
import { BotResultsSummary } from "../../common/models/bots/BotSummaryResults";
import { queries, tables } from "../constants";
import { query, ref } from "../database/utils";
import { strats } from "../includes";
import { sym } from "../services";


/**
 * Manages result sets generated by bot runs.
 */
export class ResultsService {

    /**
     * Returns the latest result set for a particular instance
     * @param instanceId 
     */
    async getLatestResultsForBot(instanceId: string): Promise<BotResultsSummary> {
        const res = await query(queries.RESULTS_GET_FOR_BOT_INSTANCE, async db => {
            const [row] = <BotResultsSummary[]>await db(tables.Results)
                .innerJoin(tables.BotRuns, ref(tables.BotRuns), "=", ref(tables.Results, "botRunId"))
                .orderBy(ref(tables.BotRuns, "created"), "desc")
                .where({ instanceId })
                .limit(1)
                ;

            if (!row) {
                return null;
            }

            return BotResultsEntity.fromRow(row);
        });

        return res.results;
    }

    /**
     * Saves results for a bot run.
     * @param botRunId 
     * @param results 
     * @returns 
     */
    async addResultsForBotRun(botRunId: string, results: BotResultsSummary): Promise<BotResultsSummary> {
        const { from, instanceId, to, symbols, runId } = results;
        if (runId !== botRunId) {
            throw new Error(`Mismatched bot run IDs`);
        }

        const [base, quote] = sym.parseSymbolPair(symbols);

        const props: Partial<BotResults> = {
            exchangeId: env.PRIMO_DEFAULT_EXCHANGE,
            baseSymbolId: base,
            quoteSymbolId: quote,
            botRunId,
            from,
            to,
            results,
        };

        const record = await query(queries.RESULTS_ADD, async db => {
            const [row] = <BotResults[]>await db(tables.Results)
                .insert(props)
                .returning("*")
                ;

            return BotResultsEntity.fromRow(row);
        });

        return null;
    }
}
